### ISSUE TITLE
feat(resident, employee): better period of residency input

### ISSUE THREAD

**Issue by itsmenewbie03** [Toshiven/online-appointment-and-certificate-generator#38]
### Description
In relation with itsmenewbie03/appt-cert-gen-api#12, the current period of residency gives too much control to the user and makes it hard to get properly structured input.  

### Proposed Approach

    Two text input fields: one for the numeric value and another for the unit.
    Labels for each field: "Value" and "Unit".
    A dropdown menu for the "Unit" field with options like "Seconds", "Minutes", "Hours", "Days", "Weeks", "Months", "Years".

Benefits:

    Users can't accidentally enter a unit in the value field.
    Backend can directly parse the numeric value and the selected unit from separate fields.

**Comment by itsmenewbie03** [comment]
@Toshiven  could you prioritize this one? so tomorrow i can work on the birthday validation in the backend.

**Comment by Toshiven** [comment]
> @Toshiven could you prioritize this one? so tomorrow i can work on the birthday validation in the backend.

Aight, I will have this done by today.

**Comment by itsmenewbie03** [comment]
This should reopened as `dashboard/admin/walk-in` does not implement this.
