### ISSUE TITLE
feat(create, resident-db):  redirect to resident-db after adding resident

### ISSUE THREAD

**Issue by Toshiven** [Toshiven/online-appointment-and-certificate-generator#40]
The current approach to creating a resident in the resident database is such that once it is created, it remains in the creation form. To streamline the process, it would be better to have it transition back to the resident database interface upon creation.

**Comment by itsmenewbie03** [comment]
I will close this as f60aba9 fully implements this.
Thanks to @BrendylSingayao00 .
